// ギャラリー用のモックデータ型
export interface CompDynamGalleryItem {
  functionLatex: string;
  initialValueLatex: string;
  iterations: number;
  center: [number, number];
  radius: number;
}

const quadraticData: CompDynamGalleryItem[] = [
  {
    functionLatex: "z^2-0.6-0.42i",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 1.7,
  },
  {
    functionLatex: "z^2+0.635i",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 1.5,
  },
  {
    functionLatex: "z^2+0.395+0.2i",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 1.5,
  },
  {
    functionLatex: "z^2-0.123+0.745i",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 1.5,
  },
  {
    functionLatex: "z^2-0.77+0.1i",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 1.7,
  },
  {
    functionLatex: "z^2-1",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 1.8,
  },
  {
    functionLatex: "z^2+i",
    initialValueLatex: "c",
    iterations: 15,
    center: [0, 0],
    radius: 1.5,
  },
  {
    functionLatex: "z^2-1.755",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 2,
  },
  {
    functionLatex: "z^2+z",
    initialValueLatex: "c",
    iterations: 50,
    center: [-0.5, 0],
    radius: 1.5,
  },
  {
    functionLatex: "z^2-z",
    initialValueLatex: "c",
    iterations: 50,
    center: [0.5, 0],
    radius: 1.8,
  },
  {
    functionLatex: "z^2-0.8-0.1i",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 1.8,
  },
  {
    functionLatex: "z^2-z-0.1+0.2i",
    initialValueLatex: "c",
    iterations: 50,
    center: [0.5, 0],
    radius: 1.8,
  },
  {
    functionLatex: "z^2-iz",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0.5],
    radius: 1.5,
  },
];

const polynomialData: CompDynamGalleryItem[] = [
  {
    functionLatex: "z^3-i",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, -1 / 6],
    radius: 1.5,
  },
  {
    functionLatex: "iz^2+0.6+0.5i",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 1.7,
  },
  {
    functionLatex: "z^3+0.54+0.2i",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 1.3,
  },
  {
    functionLatex: "z^4+iz^3-iz^2+z",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, -0.2],
    radius: 1.5,
  },
  {
    functionLatex: "iz^4+z^3+iz^2+z",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0.2],
    radius: 1.8,
  },
  {
    functionLatex: "iz^3+0.73",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, -0.14],
    radius: 1.3,
  },
  {
    functionLatex: "iz^4+0.74",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 1.3,
  },
  {
    functionLatex: "iz^5+0.75",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0.06],
    radius: 1.3,
  },
];

const binomialRationalData: CompDynamGalleryItem[] = [
  {
    functionLatex: "z^7-\\frac{0.472}{z}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 1.3,
  },
  {
    functionLatex: "z^5-\\frac{0.385}{z}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 1.3,
  },
  {
    functionLatex: "z^3-\\frac{0.25}{z}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 1.3,
  },
  {
    functionLatex: "z^2-\\frac{10^{-6}}{z}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 1.2,
  },
  {
    functionLatex: "z^3-\\frac{0.03}{z}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 1.2,
  },
  {
    functionLatex: "z^4-\\frac{0.05}{z}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 1.2,
  },
  {
    functionLatex: "z^5-\\frac{0.08}{z}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 1.2,
  },
  {
    functionLatex: "z^6-\\frac{0.14}{z}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 1.2,
  },
  {
    functionLatex: "z^7-\\frac{0.2}{z}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 1.2,
  },
  {
    functionLatex: "z^8-\\frac{0.23}{z}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 1.2,
  },
  {
    functionLatex: "z^9-\\frac{0.3}{z}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 1.2,
  },
  {
    functionLatex: "z^2+\\frac{10^{\\cos t-2}}{z}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 1.2,
  },
  {
    functionLatex: "z^2+\\frac{0.09}{z}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 1.2,
  },
  {
    functionLatex: "z^2+\\frac{0.083}{z^2}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 1.2,
  },
  {
    functionLatex: "z^2+\\frac{0.067}{z^3}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 1.2,
  },
  {
    functionLatex: "z^2+\\frac{0.055}{z^4}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 1.2,
  },
  {
    functionLatex: "z^2+\\frac{0.047}{z^5}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 1.2,
  },
  {
    functionLatex: "z^2+\\frac{0.042}{z^6}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 1.2,
  },
  {
    functionLatex: "z^2+\\frac{0.037}{z^7}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 1.2,
  },
  {
    functionLatex: "z^2+\\frac{0.033}{z^8}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 1.2,
  },
  {
    functionLatex: "z^2+\\frac{0.03}{z^9}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 1.2,
  },
  {
    functionLatex: "z^2+\\frac{0.028}{z^{10}}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 1.2,
  },
  {
    functionLatex: "z^2+\\frac{0.027}{z^{11}}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 1.2,
  },
  {
    functionLatex: "z^2+\\frac{0.027}{z^{12}}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 1.2,
  },
];

const generalRationalData: CompDynamGalleryItem[] = [
  {
    functionLatex: "\\frac{2z}{z^2+e^{\\frac{it}{2}-2}}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 2,
  },
  {
    functionLatex: "\\frac{2z}{z^2+1.7^{i+1}}",
    initialValueLatex: "9^{\\cos \\frac{t}{2}}c",
    iterations: 50,
    center: [0, 0],
    radius: 1,
  },
  {
    functionLatex: "\\frac{z^3-z-i}{z^2-z-1}",
    initialValueLatex: "c",
    iterations: 50,
    center: [-1, -0.5],
    radius: 3,
  },
  {
    functionLatex: "\\frac{2z^2-i}{z^3-z}",
    initialValueLatex: "9^{\\cos \\frac{t}{2}}c",
    iterations: 50,
    center: [0, 0],
    radius: 1,
  },
  {
    functionLatex: "\\frac{2z^2-i}{z^3-z^2+1}",
    initialValueLatex: "9^{\\cos \\frac{t}{2}}c",
    iterations: 50,
    center: [0, 0],
    radius: 1,
  },
  {
    functionLatex: "\\frac{z^2-1}{z^2-z-i}",
    initialValueLatex: "9^{\\cos \\frac{t}{2}}c",
    iterations: 50,
    center: [0, 0],
    radius: 1,
  },
  {
    functionLatex: "-\\frac{2i}{z^2+i}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 3,
  },
  {
    functionLatex: "\\frac{z^3-i}{z^3+i}-0.6",
    initialValueLatex: "c",
    iterations: 50,
    center: [0.3, 0.5],
    radius: 3.3,
  },
  {
    functionLatex: "\\frac{z^4-i}{z^4+i}-0.5",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 2,
  },
  {
    functionLatex: "\\frac{z^5-i}{z^5+i}-0.5",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, -0.1],
    radius: 2,
  },
  {
    functionLatex: "\\frac{z^6-i}{z^6+i}-0.4",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 1.8,
  },
  {
    functionLatex: "\\frac{z^7-i}{z^7+i}-0.4",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0.1],
    radius: 1.7,
  },
  {
    functionLatex: "\\frac{z^8-i}{z^8+i}-0.3",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 1.7,
  },
  {
    functionLatex: "z-\\frac{z}{z^2-3i}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 3,
  },
  {
    functionLatex: "z-\\frac{z}{z^3-3i}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 3,
  },
  {
    functionLatex: "z-\\frac{z}{z^4-3i}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 3,
  },
  {
    functionLatex: "z-\\frac{z}{z^5-3i}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 3,
  },
  {
    functionLatex: "-z-\\frac{z}{z-3i}",
    initialValueLatex: "c",
    iterations: 100,
    center: [0, 0],
    radius: 3,
  },
  {
    functionLatex: "-z-\\frac{z}{z^2-3i}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 3,
  },
  {
    functionLatex: "-z-\\frac{z}{z^3-3i}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 3,
  },
  {
    functionLatex: "-z-\\frac{z}{z^4-3i}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 2.5,
  },
  {
    functionLatex: "-z-\\frac{z}{z^5-3i}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 2,
  },
  {
    functionLatex:
      "z-\\frac{\\left(z^2-1\\right)\\left(z^2-i\\right)}{2z\\left(2z-1\\right)}",
    initialValueLatex: "c",
    iterations: 50,
    center: [1.7, 0],
    radius: 5,
  },
  {
    functionLatex: "\\frac{z}{z^2-0.7i}",
    initialValueLatex: "9^{\\cos \\frac{t}{2}}c",
    iterations: 50,
    center: [0, 0],
    radius: 1,
  },
  {
    functionLatex: "\\frac{z}{z^2+0.1-0.9i}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 2,
  },
  {
    functionLatex: "\\frac{z}{z^2+0.05-0.2i}",
    initialValueLatex: "9^{\\cos \\frac{t}{2}}c",
    iterations: 50,
    center: [0, 0],
    radius: 2,
  },
  {
    functionLatex: "\\frac{z}{z^3-0.9-0.08i}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 2,
  },
  {
    functionLatex: "z^2-\\frac{0.12i}{z}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, -0.1],
    radius: 1.3,
  },
  {
    functionLatex: "\\frac{1}{z^2-0.6}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 2,
  },
  {
    functionLatex: "\\frac{1}{z^2-0.6i}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 2,
  },
];

const realPeriodicData: CompDynamGalleryItem[] = [
  {
    functionLatex: "\\sin z",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 5,
  },
  {
    functionLatex: "\\cos z",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 5,
  },
  {
    functionLatex: "1.3\\sinh iz",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 5,
  },
  {
    functionLatex: "e^{\\frac{i\\pi }{4}}\\csc z",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 4,
  },
  {
    functionLatex: "e^{\\sin z}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 6,
  },
  {
    functionLatex: "e^{\\cos2z}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 3,
  },
  {
    functionLatex: "e^{\\sin z+0.01+0.2i}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 0.02,
  },
  {
    functionLatex: "\\cos\\left(z-\\cos1.8z\\right)",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 2,
  },
  {
    functionLatex: "\\sinh\\left(0.5\\cos z+i\\sin z\\right)",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 3,
  },
  {
    functionLatex: "\\sin\\left(\\cos2z\\right)",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 3,
  },
  {
    functionLatex: "e^{\\sin\\left(z+0.01+0.2i\\right)}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 0.3,
  },
  {
    functionLatex: "\\frac{\\cos z}{\\sin 2z}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 0.5,
  },
  {
    functionLatex: "\\left(\\sin z+\\tan z\\right)\\tan z",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 2,
  },
  {
    functionLatex: "\\cos z+\\sin z",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 2,
  },
  {
    functionLatex: "0.6e^{i\\sin z}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 4,
  },
  {
    functionLatex: "\\frac{e^{5i}}{2}\\cos 2z",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 3,
  },
  {
    functionLatex: "\\cos\\left(z-i\\right)",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 1],
    radius: 5,
  },
  {
    functionLatex: "\\sin\\frac{1}{z}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 5,
  },
];

const imaginaryPeriodicData: CompDynamGalleryItem[] = [
  {
    functionLatex: "\\sinh z",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 5,
  },
  {
    functionLatex: "e^{-z}",
    initialValueLatex: "c",
    iterations: 50,
    center: [-4, 0],
    radius: 9,
  },
  {
    functionLatex: "\\cos e^z",
    initialValueLatex: "c",
    iterations: 50,
    center: [3, 0],
    radius: 6,
  },
  {
    functionLatex: "\\frac{\\cosh z-i}{\\cosh z-1}",
    initialValueLatex: "c",
    iterations: 100,
    center: [0, 0],
    radius: 2,
  },
  {
    functionLatex: "\\frac{\\cosh z+i}{\\cosh z-1}",
    initialValueLatex: "c",
    iterations: 100,
    center: [0, 0],
    radius: 2,
  },
  {
    functionLatex: "\\frac{\\sinh z-i}{\\cosh z-1}",
    initialValueLatex: "c",
    iterations: 100,
    center: [0, 0],
    radius: 2,
  },
  {
    functionLatex: "\\frac{\\sinh z-1}{\\sinh z+1}",
    initialValueLatex: "c",
    iterations: 100,
    center: [0, 0],
    radius: 1,
  },
  {
    functionLatex: "\\cosh z-2",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 8,
  },
];

const argumentPeriodicData: CompDynamGalleryItem[] = [
  {
    functionLatex: "\\cos\\frac{20i}{z}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 9,
  },
  {
    functionLatex: "\\cos\\frac{20i}{z^2}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 4,
  },
  {
    functionLatex: "\\cos\\frac{20i}{z^3}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 3,
  },
  {
    functionLatex: "\\cos\\frac{20}{z^3}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 3,
  },
  {
    functionLatex: "0.1\\left(\\cos z+\\cosh z\\right)+3.5i",
    initialValueLatex: "c",
    iterations: 100,
    center: [0, 0],
    radius: 6,
  },
  {
    functionLatex: "\\left(\\cos z\\right)\\left(\\cosh z\\right)+1",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 2.5,
  },
  {
    functionLatex: "z-\\frac{\\tan z}{3}",
    initialValueLatex: "c",
    iterations: 100,
    center: [0, 0],
    radius: 3,
  },
];

const periodicLikeData: CompDynamGalleryItem[] = [
  {
    functionLatex: "\\frac{\\cos z^2}{9z}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 3,
  },
  {
    functionLatex: "z+\\tanh z",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 1,
  },
  {
    functionLatex: "z+i\\tanh z",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 2,
  },
  {
    functionLatex: "\\csc z^2",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 3,
  },
  {
    functionLatex: "\\sec z^2",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 3,
  },
  {
    functionLatex: "\\sin\\frac{z}{\\cos z}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 4,
  },
  {
    functionLatex: "\\cos\\frac{z}{\\cos z}",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 4,
  },
  {
    functionLatex: "e^{i-z}+z",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 9,
  },
  {
    functionLatex: "\\frac{1}{z}-0.1\\tanh z",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 2,
  },
];

const otherData: CompDynamGalleryItem[] = [
  {
    functionLatex: "e^{\\frac{i}{z}}",
    initialValueLatex: "c",
    iterations: 50,
    center: [-0.14, -0.4],
    radius: 0.5,
  },
  {
    functionLatex: "e^{\\frac{1}{z}}",
    initialValueLatex: "c",
    iterations: 50,
    center: [-0.16, 0],
    radius: 0.5,
  },
  {
    functionLatex: "\\sin\\left(\\left(0.6+0.3i\\right)z\\right)",
    initialValueLatex: "c",
    iterations: 50,
    center: [0, 0],
    radius: 8,
  },
];

export const galleryData: CompDynamGalleryItem[] = [
  ...quadraticData,
  ...polynomialData,
  ...binomialRationalData,
  ...generalRationalData,
  ...realPeriodicData,
  ...imaginaryPeriodicData,
  ...argumentPeriodicData,
  ...periodicLikeData,
  ...otherData,
  {
    functionLatex: "z^2+c",
    initialValueLatex: "0",
    iterations: 50,
    center: [-0.5, 0],
    radius: 1.5,
  },
  // https://x.com/TOMOQ8192/status/1748551565932216410
];
