/**
 * 各アプリの app.config.ts を走査し appList.generated.ts を生成する
 *
 * 使用方法:
 *   pnpm generate:app-list
 */

import { existsSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import type { AppConfig } from "../src/lib/apps/types";

const APPS_ROOT = resolve(__dirname, "../src/app/apps");
const OUTPUT = resolve(__dirname, "../src/lib/apps/appList.generated.ts");

function findAppConfigFiles(dir: string): string[] {
  const results: string[] = [];

  for (const entry of readdirSync(dir)) {
    const fullPath = join(dir, entry);
    if (!statSync(fullPath).isDirectory()) {
      continue;
    }

    const configPath = join(fullPath, "app.config.ts");
    if (existsSync(configPath)) {
      results.push(configPath);
      continue;
    }

    results.push(...findAppConfigFiles(fullPath));
  }

  return results;
}

/** `(maths)/compdynam` → `compdynam`, `(experimental)/three/fiber` → `three/fiber` */
function pathFromConfigFile(configFile: string): string {
  const relativePath = relative(APPS_ROOT, dirname(configFile));
  return relativePath
    .split("/")
    .filter((segment) => !/^\(.+\)$/.test(segment))
    .join("/");
}

function serializeEntry(config: AppConfig): string {
  const lines = [
    `    appName: ${JSON.stringify(config.appName)},`,
    `    status: ${JSON.stringify(config.status)},`,
    `    tags: ${JSON.stringify(config.tags)},`,
  ];

  if (config.description) {
    lines.push(`    description: ${JSON.stringify(config.description)},`);
  }
  if (config.sortOrder !== undefined) {
    lines.push(`    sortOrder: ${config.sortOrder},`);
  }

  return lines.join("\n");
}

async function main() {
  const configFiles = findAppConfigFiles(APPS_ROOT).sort();

  if (configFiles.length === 0) {
    console.error("app.config.ts が見つかりません");
    process.exit(1);
  }

  const entries: { path: string; config: AppConfig }[] = [];

  for (const configFile of configFiles) {
    const appPath = pathFromConfigFile(configFile);
    const pageFile = join(dirname(configFile), "page.tsx");

    if (!existsSync(pageFile)) {
      console.warn(`  ⚠ ${appPath}: page.tsx がありません (${configFile})`);
    }

    const mod = await import(pathToFileURL(configFile).href);
    const config = mod.appConfig as AppConfig | undefined;

    if (!config) {
      console.error(`  ✗ ${appPath}: appConfig の export がありません`);
      process.exit(1);
    }

    entries.push({ path: appPath, config });
    console.log(`  ✓ ${appPath}`);
  }

  entries.sort((a, b) => {
    const orderA = a.config.sortOrder ?? Number.MAX_SAFE_INTEGER;
    const orderB = b.config.sortOrder ?? Number.MAX_SAFE_INTEGER;
    if (orderA !== orderB) {
      return orderA - orderB;
    }
    return a.path.localeCompare(b.path);
  });

  const body = entries
    .map(({ path, config }) => {
      return `  ${JSON.stringify(path)}: {\n${serializeEntry(config)}\n  },`;
    })
    .join("\n");

  const output = `// AUTO-GENERATED by scripts/generate-app-list.ts — do not edit manually.
// Source: src/app/apps/**/app.config.ts

import type { AppList } from "./types";

export const appList = {
${body}
} satisfies AppList;
`;

  writeFileSync(OUTPUT, output, "utf8");
  console.log(`\n✓ ${entries.length} 件 → ${relative(process.cwd(), OUTPUT)}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
