// AUTO-GENERATED by scripts/generate-app-list.ts — do not edit manually.
// Source: src/app/apps/**/app.config.ts

import type { AppList } from "./types";

export const appList = {
  "compdynam": {
    appName: "CompDynam",
    status: "published",
    tags: ["maths","fractal"],
    sortOrder: 1,
  },
  "graph-2d": {
    appName: "Graph 2D",
    status: "published",
    tags: ["maths"],
    sortOrder: 2,
  },
  "polychora": {
    appName: "Polychora",
    status: "published",
    tags: ["maths","geometry"],
    sortOrder: 3,
  },
  "tiling": {
    appName: "Tiling",
    status: "published",
    tags: ["maths","geometry"],
    sortOrder: 4,
  },
  "linear-attractor-2d": {
    appName: "Linear Attractor 2D",
    status: "published",
    tags: ["maths","fractal"],
    description: "複数のアフィン変換による2次元アトラクターを観察できるページ",
    sortOrder: 5,
  },
  "mandel-match": {
    appName: "Mandel Match",
    status: "published",
    tags: ["maths","fractal"],
    sortOrder: 6,
  },
  "graph-3d": {
    appName: "Graph 3D",
    status: "published",
    tags: ["maths"],
    sortOrder: 7,
  },
  "linear-attractor": {
    appName: "Linear Attractor",
    status: "published",
    tags: ["maths","fractal"],
    description: "複数のアフィン変換による3次元アトラクターを観察できるページ",
    sortOrder: 8,
  },
  "gmowski-mira-attractor": {
    appName: "Gmowski-Mira Attractor",
    status: "lab",
    tags: ["maths"],
    sortOrder: 9,
  },
  "glslfilter": {
    appName: "GLSL Filter",
    status: "published",
    tags: ["utility","webgl"],
    sortOrder: 10,
  },
  "chaosgame": {
    appName: "Chaos Game",
    status: "lab",
    tags: ["maths","fractal"],
  },
  "diceroll": {
    appName: "Dice Roll",
    status: "lab",
    tags: ["utility"],
  },
  "h2tiling": {
    appName: "H2 Tiling",
    status: "lab",
    tags: ["maths","geometry"],
  },
  "lifegame": {
    appName: "Life Game",
    status: "lab",
    tags: ["maths"],
  },
  "polyhedra": {
    appName: "Polyhedra",
    status: "lab",
    tags: ["maths","geometry"],
  },
  "recursivetree": {
    appName: "Recursive Tree",
    status: "lab",
    tags: ["maths","fractal"],
  },
} satisfies AppList;
